name: Contexts
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.actor}}"
      - run: echo "${{ github.event_name}}"
      - run: echo "${{ github.event.pull_request.title}}"
      - run: echo "${{ github.workflow}}"
      - run: echo "${{ github.repository}}"
      - run: echo "${{ github.ref}}"
      - run: echo "${{ github.sha}}"
      - run: echo "${{ github.repository_owner}}"
      - run: echo "${{ github.api_url}}"
      - run: echo "${{ runner.name}}"
      - run: echo "${{ runner.os}}"
      - run: echo "${{ runner.temp}}"
