name: Compare functions
on: push
jobs:
  compare:
    runs-on: ubuntu-latest
    steps:
      - run: printenv | grep '_FUNC'
        env:
          CONTAINS_FUNC: ${{ contains('Hello', 'ell')}}
          STARTS_WITH_FUNC: ${{ startsWith('Hello', 'Hel')}}
          ENDS_WITH_FUNC: ${{ endsWith('Hello', 'llo')}}