name: LogLevel

on:
  workflow_dispatch:
    inputs:
      log-level:
        type: choice
        options:
          - debug
          - info
          - warning
          - error

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.log-level}}"